services:
    postgres:
        image: postgres:18
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME:-feev}
            POSTGRES_PASSWORD: ${DATABASE_USERNAME:-secret}
            POSTGRES_DB: ${DATABASE_USERNAME:-feevcheckout}
    api:
        build:
            context: .
        restart: unless-stopped
        ports:
            - 5265:5265
        volumes:
            - ./:/app
            - /app/bin
            - /app/obj
        depends_on:
            - postgres
        environment:
            ASPNETCORE_ENVIRONMENT: ${APP_ENV:-Development}
volumes:
    postgres_data:
